local cfg = {}

cfg.items = {
	["bombacaseira"] = { "Bomba fatta in casa",4.0 },
	["pecadecarro"] = { "Parte auto",0.1 },
	["R1"] = { "Yamaha R1",1.0 },
	["shield"] = { "Scudo",1.1 },
	["colete"] = { "Veste",1.1 },
	["aliancaouro"] = { "Anello d'oro",0.7 },
	["aliancaprata"] = { "Fede nuziale in argento",0.7 },
	["paraliancaouro"] = { "coppia di anelli di nozze d'oro",0.7 },
	["paraliancaprata"] = { "coppia di fedi nuziali in argento",0.7 },
	["compeletronico"] = { "Comp. elettronico",0.5 },
	["parafuso"] = { "Parafuso",1.0 },
	["arame"] = { "Filo",1.0 },
	["latadetinta"] = { "Barattolo di vernice",1.0 },
	["caixadeuva"] = { "scatola di una",0.8 },
	["cordas"] = { "Corda",1 },
	["encomenda"] = { "Ordine",1.2 },
	["sacodelixo"] = { "Busta della spazzatura",2 },
	["alianca"] = { "Alleanza",0 },
	["bende"] = { "Bende",0.0 },
	["adrenalina"] = { "Adrenalina",2.0 },
	["melzinho"] = { "Melzinho",0.0 },
	["uvas"] = { "Uva",0.5 },
	["lanche"] = { "Merenda",0.5 },
	["fardo"] = { "balla di birra",2 },
	["sefodex"] = { "Sefodex",0 },
	["nokusin"] = { "Nokusin",0 },
	["glicoanal"] = { "glicoanale",0 },
	["cerveja"] = { "Birra",0.7 },
	["tequila"] = { "Tequila",0.7 },
	["vodka"] = { "Vodka",0.7 },
	["whisky"] = { "Whisky",0.7 },
	["conhaque"] = { "Conhaque",0.7 },
	["absinto"] = { "Absinto",0.7 },
	["denarosporco"] = { "Soldi sporchi",0 },
	["dinheiroempacotado"] = { "denaro confezionato",0.00001 },
	["repairkit"] = { "Kit Riparazione",1 },
	["funcionalpol"] = { "Scheda funzionale della polizia",0.0 },
	["algemas"] = { "Manette",1 },
	["capuz"] = { "Capuccino",0.5 },
	["lockpick"] = { "grimaldello",1 },
	["jornal"] = { "Giornale",0.8 },
	["masterpick"] = { "Capolavoro",1 },
	["militec"] = { "Miltec-1",0.8 },
	["isca"] = { "Esca",0.0 },
	["dourado"] = { "D'oro",0.0 },
	["corvina"] = { "Corvina",0.0 },
	["salmao"] = { "Salmone",0.0 },
	["pacu"] = { "pacu",0.0 },
	["pintado"] = { "Dipinto",0.0 },
	["pirarucu"] = { "Pirarucu",0.0 },
	["tilapia"] = { "Tilapia",0.0 },
	["tucunare"] = { "basso di pavone",0.0 },
	["lambari"] = { "Lambari",0.0 },
	["energetico"] = { "Energetico",0.0 },
	["chocolate"] = { "Cioccolato",0.0 },
	["zaino"] = { "Zaino",0 },
	["folhademaconha"] = { "Foglia di marijuana",0.0 },
	["maconhamacerada"] = { "Marijuana lavorata",0.0 },
	["baseado"] = { "Canna",0.0 },

	["material9mm"] = { "Materiale 9mm",0.20  },
	["material762"] = { "Materiale  7.62",0.35 },
	["capsula9mm"] = { "capsula di 9MM",0.20 },
	["capsula762"] = { "capsula di 7.62",0.25  },
	["polvora9mm"] = { "polvere da sparo di 9MM",0.20 },
	["polvora762"] = { "polvere da sparo di 7.62",0.25 },
	
	["pecadearma"] = { "Pezzo d'arma",0.25 },
	["pecadetec"] = { "Pezzo di TEC",0.25 },
	["pecademp5"] = { "Pezzo di MP5",0.25 },
	["pecadeak"] = { "Pezzo di AK",0.25 },
	["pecadeg3"] = { "Pezzo di G36",0.25 },

	["armacaodearma"] = { "Componente Pistola",0.25 },
	["armacaodescar"] = { "Componente SCAR",0.25 },
	["armacaodeg3"] = { "Componente G36",0.25 },
	["armacaodemp5"] = { "Componente MP5",0.25 },
	["armacaodetec"] = { "Componente TEC-9",0.25 },	

	["materialarmas"] = { "Materiale per armi",0.20 },
	["materialak"] = { "Materiale di AK",0.35 },
	["materialg3"] = { "Materiale di G36",0.30 },
	["materialmp5"] = { "Materiale di MP5",0.20 },
	["materialtec"] = { "Materiale di TEC-9",0.20 },

	["pneumatici"] = { "Pneumatici", 0.2},

	["candeggina"] = { "Candeggina",0.2 },
	["candegginamodificata"] = { "Candeggina modificata",0.4 },
	["capsula"] = { "Capsula",0.03 },
	["polvora"] = { "Polvere da sparo",0.03 },
	["pendrive"] = { "Chiavetta USB",0.1 },
	["notebook"] = { "Notebook",1.0 },
	["relogioroubado"] = { "Orologio rubato",0.3 },
	["pulseiraroubada"] = { "Braccialetto rubato",0.2 },
	["anelroubado"] = { "Anello rubato",0.2 },
	["colarroubado"] = { "Collana rubata",0.2 },
	["brincoroubado"] = { "Orecchino rubato",0.2 },
	["carteiraroubada"] = { "Portafoglio rubato",0.2 },
	["tabletroubado"] = { "tablet rubato",0.2 },
	["sapatosroubado"] = { "Scarpe rubate",0.2 },
	["k9"] = { "K9",0.0 },
	["essenciadeecstasy"] = { "essenza dell'ecstasy",0.8 },
	["pastadeecstasy"] = { "pasta di ecstasy",0.8 },
	["ecstasy"] = { "Ecstasy",0.0 },
	["fungo"] = { "Fungo",0.8 },
	["dietilamina"] = { "Dietilammina",0.8 },
	["lancaperfume"] = { "lancia profumo",0.8 },
	["canabidinol"] = { "Cannabidinolo",0.8 },
	["gps"] = { "GPS",0.8 },
	["ticketazione"] = { "Ticket azione",0.3 },
	["anfetamina"] = { "Anfetamina",0.0 },
	["krokodil"] = { "Krokodil",0.0 },
	["logsinvasao"] = { "Registri di invasione",0.1 },
	["keysinvasao"] = { "Keys per l'invasione",1.0 },
	["pendriveinformacoes"] = { "Chiavetta USB con informazioni",0.1 },
	["acessodeepweb"] = { "Accesso al Deep Web",1.0 },
	["ouro"] = { "Oro",0.25 },
	["bronze"] = { "Bronzo",0.20 },
	["ferro"] = { "Ferro",0.30 },
	["radio"] = { "Radio",0.0 },
	["arance"] = { "Arance",1.0 },
	["serra"] = { "Serra",5.0 },
	["furadeira"] = { "Trapano",5.0 },
	["c4"] = { "C-4",5.0 },
	["vestiti"] = { "Vestiti",1.0 },
	["xerelto"] = { "Xarelto",0.1 },
  	["coumadin"] = { "Coumadin",0.1 },
	["identidade"] = { "Identità",0 },
	["keycard"] = { "Carta clonata",0.1 },
	["placa"] = { "Scheda",0.6 },
	["aneldecompromisso"] = { "Anello di impegno",1.0 },
	["colardeperolas"] = { "Collana di perle",1.0 },
	["pulseiradeouro"] = { "Braccialetto d'oro",1.0 },
	["cioccolato"] = { "Cioccolato",1.0 },
	["pirulito"] = { "Lecca-lecca",1.0 },
	["bateria"] = { "Batteria",0.3 },
	["cobre"] = { "Rame",0.3 },
	["plastico"] = { "Plastica",0.3 },
	["borracha"] = { "Gomma",0.3 },
	["linha"] = { "Linea",0.3 },
	["pano"] = { "Stoffa",0.3 },
	["tecido"] = { "Tessuto",0.3 },
	["algodao"] = { "Cotone",0.3 },
	["couro"] = { "Pelle",0.3 },
	["vidro"] = { "Vetro",0.3 },
	["pilha"] = { "Pila",0.3 },
	["fioeletronico"] = { "Filo elettronico",0.3 },
	["lata"] = { "Stagno",0.3 },
	["buque"] = { "Bouquet di fiori",1.0 },
	["cellulare"] = { "Cellulare",1.0 },
	["wammo|WEAPON_PISTOL_MK2"] = { "M.FN Pistol MK2",0.05 },
	["wammo|WEAPON_COMBATPISTOL"] = { "M.Glock 17",0.05 },
	["wammo|WEAPON_HEAVYRIFLE"] = { "M.Scar",0.05 },
	["wammo|WEAPON_CARBINERIFLE_MK2"] = { "M.MPX",0.05 },
	["wammo|WEAPON_SPECIALCARBINE_MK2"] = { "M.G36 MK2",0.05 },
	["wammo|WEAPON_MACHINEPISTOL"] = { "M.TEC-9",0.05 },
	["wammo|WEAPON_SNSPISTOL"] = { "M.HK P7M10",0.05 },
	["wammo|WEAPON_COMBATPDW"] = { "M.Sig Sauer MPX",0.05 },
	["wammo|WEAPON_ASSAULTSMG"] = { "M.MTAR-21",0.05 },
	["wammo|WEAPON_SMG"] = { "M.MP5",0.05 },
	["wammo|WEAPON_SMG_MK2"] = { "M.MP5 MK2",3 },
	["wammo|WEAPON_CARBINERIFLE"] = { "M.M4A1",0.05 },
	["wammo|WEAPON_HEAVYPISTOL"] = { "M.HEAVYPISTOL",0.05 },
	["wbody|WEAPON_SPECIALCARBINE_MK2"] = { "G36 MK2",3 },
	["wbody|WEAPON_COMBATPISTOL"] = { "Glock 17",1 },
	["wbody|WEAPON_HEAVYRIFLE"] = { "Scar",3 },
	["wbody|WEAPON_CARBINERIFLE_MK2"] = { "MPX",3 },
	["wbody|WEAPON_PISTOL_MK2"] = { "FN Pistol MK2",3 },
	["wbody|WEAPON_MACHINEPISTOL"] = { "TEC-9",3 },
	["wbody|WEAPON_SNSPISTOL"] = { "HK P7M10",3},
	["wbody|WEAPON_COMBATPDW"] = { "Sig Sauer MPX",3 },
	["wbody|WEAPON_ASSAULTSMG"] = { "MTAR-21",3 },
	["wbody|WEAPON_HEAVYPISTOL"] = { "HEAVYPISTOL",1 },
	["wbody|WEAPON_SMG"] = { "MP5",2 },
	["wbody|WEAPON_SMG_MK2"] = { "MP5 MK2",2 },
	["wbody|WEAPON_CARBINERIFLE"] = { "M4A1",3 },

}

local function load_item_pack(name)
	local items = module("cfg/item/"..name)
	if items then
		for k,v in pairs(items) do
			cfg.items[k] = v
		end
	end
end

load_item_pack("armamentos")

return cfg