function tvRP.getNearestVehicles(radius)
	local r = {}
	local px,py,pz = table.unpack(GetEntityCoords(PlayerPedId()))

	local vehs = {}
	local it,veh = FindFirstVehicle()
	if veh then
		table.insert(vehs,veh)
	end
	local ok
	repeat
		ok,veh = FindNextVehicle(it)
		if ok and veh then
			table.insert(vehs,veh)
		end
	until not ok
	EndFindVehicle(it)

	for _,veh in pairs(vehs) do
		local x,y,z = table.unpack(GetEntityCoords(veh))
		local distance = Vdist(x,y,z,px,py,pz)
		if distance <= radius then
			r[veh] = distance
		end
	end
	return r
end

function tvRP.getNearestVehicle(radius)
	local veh
	local vehs = tvRP.getNearestVehicles(radius)
	local min = radius+0.0001
	for _veh,dist in pairs(vehs) do
		if dist < min then
			min = dist
			veh = _veh
		end
	end
	return veh 
end

function tvRP.ejectVehicle()
	local ped = PlayerPedId()
	if IsPedSittingInAnyVehicle(ped) then
		TaskLeaveVehicle(ped,GetVehiclePedIsIn(ped),4160)
	end
end

function tvRP.isInVehicle()
	return IsPedSittingInAnyVehicle(PlayerPedId())
end
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
local vehList = {
	-- CARROS NOVOS TUNERS
	{ ['name'] = "sultan3", ['banned'] = false },
	{ ['name'] = "cypher", ['banned'] = false },
	{ ['name'] = "jester4", ['banned'] = false },
	{ ['name'] = "comet6", ['banned'] = false },
	{ ['name'] = "growler", ['banned'] = false },

	{ ['name'] = "22m5", ['banned'] = false },
	{ ['name'] = "LOclassx", ['banned'] = false },
	{ ['name'] = "novakpol", ['banned'] = false },
	{ ['name'] = "r1250pol", ['banned'] = false },
	{ ['name'] = "Wrgtr", ['banned'] = false },
	{ ['name'] = "amggtsmansory", ['banned'] = false },

	{ ['name'] = "bmwm3e36", ['banned'] = false },
	{ ['name'] = "toyotasupra", ['banned'] = false },
	{ ['name'] = "ferrarif12", ['banned'] = false },

	{ ['name'] = "vectre", ['banned'] = false },
	{ ['name'] = "zr350", ['banned'] = false },
	{ ['name'] = "calico", ['banned'] = false },
	{ ['name'] = "euros", ['banned'] = false },
	{ ['name'] = "rt3000", ['banned'] = false },

    -- CARROS ATT
	{ ['name'] = "sultan2", ['banned'] = false },
	{ ['name'] = "jugular", ['banned'] = false },
	{ ['name'] = "kanjo", ['banned'] = false },
	{ ['name'] = "asbo", ['banned'] = false },
	{ ['name'] = "club", ['banned'] = false },
	{ ['name'] = "brioso2", ['banned'] = false },
	{ ['name'] = "weevil", ['banned'] = false },
	{ ['name'] = "rrocket", ['banned'] = false },
	{ ['name'] = "stryder", ['banned'] = false },
	{ ['name'] = "manchez2", ['banned'] = false },
	{ ['name'] = "dukes3", ['banned'] = false },
	{ ['name'] = "gauntlet3", ['banned'] = false },
	{ ['name'] = "gauntlet4", ['banned'] = false },
	{ ['name'] = "gauntlet5", ['banned'] = false },
	{ ['name'] = "peyote2", ['banned'] = false },
	{ ['name'] = "yosemite2", ['banned'] = false },
	{ ['name'] = "yosemite3", ['banned'] = false },
	{ ['name'] = "caracara2", ['banned'] = false },
	{ ['name'] = "everon", ['banned'] = false },
	{ ['name'] = "hellion", ['banned'] = false },
	{ ['name'] = "outlaw", ['banned'] = false },
	{ ['name'] = "vagrant", ['banned'] = false },
	{ ['name'] = "zhaba", ['banned'] = false },
	{ ['name'] = "verus", ['banned'] = false },
	{ ['name'] = "winky", ['banned'] = false },
	{ ['name'] = "formula", ['banned'] = false },
	{ ['name'] = "formula2", ['banned'] = false },
	{ ['name'] = "openwheel1", ['banned'] = false },
	{ ['name'] = "openwheel2", ['banned'] = false },
	{ ['name'] = "landstalker2", ['banned'] = false },
	{ ['name'] = "novak", ['banned'] = false },
	{ ['name'] = "rebla", ['banned'] = false },
	{ ['name'] = "seminole2", ['banned'] = false },
	{ ['name'] = "squaddie", ['banned'] = false },
	{ ['name'] = "glendale2", ['banned'] = false },
	{ ['name'] = "coquette4", ['banned'] = false },
	{ ['name'] = "drafter", ['banned'] = false },
	{ ['name'] = "komoda", ['banned'] = false },
	{ ['name'] = "imorgon", ['banned'] = false },
	{ ['name'] = "issi7", ['banned'] = false },
	{ ['name'] = "locust", ['banned'] = false },
	{ ['name'] = "neo", ['banned'] = false },
	{ ['name'] = "paragon", ['banned'] = false },
	{ ['name'] = "penumbra2", ['banned'] = false },
	{ ['name'] = "sugoi", ['banned'] = false },
	{ ['name'] = "vstr", ['banned'] = false },
	{ ['name'] = "veto", ['banned'] = false },
	{ ['name'] = "veto2", ['banned'] = false },
	{ ['name'] = "dynasty", ['banned'] = false },
	{ ['name'] = "peyote3", ['banned'] = false },
	{ ['name'] = "retinue2", ['banned'] = false },
	{ ['name'] = "nebula", ['banned'] = false },
	{ ['name'] = "zion3", ['banned'] = false },
	{ ['name'] = "emerus", ['banned'] = false },
	{ ['name'] = "furia", ['banned'] = false },
	{ ['name'] = "krieger", ['banned'] = false },
	{ ['name'] = "s80", ['banned'] = false },
	{ ['name'] = "thrax", ['banned'] = false },
	{ ['name'] = "tigon", ['banned'] = false },
	{ ['name'] = "zorrusso", ['banned'] = false },
	{ ['name'] = "slamtruck", ['banned'] = false },
	{ ['name'] = "youga3", ['banned'] = false },

	-- VIPS MOTOS
	{ ['name'] = "f800", ['banned'] = false },
	{ ['name'] = "gs1200", ['banned'] = false },
	{ ['name'] = "tiger", ['banned'] = false },
	{ ['name'] = "africat", ['banned'] = false },
	{ ['name'] = "cbr1000rrr", ['banned'] = false },
	{ ['name'] = "h2carb", ['banned'] = false },
	{ ['name'] = "pcx", ['banned'] = false },
	{ ['name'] = "xt700", ['banned'] = false },
	{ ['name'] = "r1", ['banned'] = false },
	{ ['name'] = "r6", ['banned'] = false },
	{ ['name'] = "cb500x", ['banned'] = false },

	-- VIPS
	{ ['name'] = "xnsgt", ['banned'] = false },
	{ ['name'] = "bmci", ['banned'] = false },
	{ ['name'] = "bmwm4gts", ['banned'] = false },
	{ ['name'] = "audirs7", ['banned'] = false },
	{ ['name'] = "porscherusher", ['banned'] = false },
	{ ['name'] = "hiluxsw4", ['banned'] = false },

	{ ['name'] = "bmwi8", ['banned'] = false },
	{ ['name'] = "ferrariitalia", ['banned'] = false },
	{ ['name'] = "765lt", ['banned'] = false },
	{ ['name'] = "lamborghinihuracan", ['banned'] = false },
	{ ['name'] = "nissangtr", ['banned'] = false },
	{ ['name'] = "lancerevolutionx", ['banned'] = false },
	{ ['name'] = "mazdarx7", ['banned'] = false },
	{ ['name'] = "nissangtrnismo", ['banned'] = false },
	{ ['name'] = "nissanskyliner34", ['banned'] = false },
	{ ['name'] = "nissanskylinerocket", ['banned'] = false },
	{ ['name'] = "rmodx6", ['banned'] = false },
	{ ['name'] = "gt2rsmr", ['banned'] = false },
	{ ['name'] = "teslaprior", ['banned'] = false },
	{ ['name'] = "mlnovitec", ['banned'] = false },
	{ ['name'] = "brz13", ['banned'] = false },
	{ ['name'] = "golfgti7", ['banned'] = false },
	{ ['name'] = "pturismo", ['banned'] = false },
	{ ['name'] = "pcs18", ['banned'] = false },
	{ ['name'] = "ben17", ['banned'] = false },
	{ ['name'] = "amarok", ['banned'] = false },
	{ ['name'] = "bmwm8", ['banned'] = false },
	{ ['name'] = "lancerevolution9", ['banned'] = false },
	{ ['name'] = "urus", ['banned'] = false },

	{ ['name'] = "f8t", ['banned'] = false },
	{ ['name'] = "r820", ['banned'] = false },
	{ ['name'] = "mercedesgt63", ['banned'] = false },
	-- polizia SUL
	{ ['name'] = "vra3", ['banned'] = true },
	{ ['name'] = "vra4", ['banned'] = true },
	{ ['name'] = "vrq8", ['banned'] = true },
	{ ['name'] = "vrrs6", ['banned'] = true },
	{ ['name'] = "vrrs6av", ['banned'] = true },
	{ ['name'] = "vrrs5", ['banned'] = true },
	{ ['name'] = "vrr8", ['banned'] = true },
	{ ['name'] = "vrraptor", ['banned'] = true },
	{ ['name'] = "vrtahoe", ['banned'] = true },
	{ ['name'] = "vrdm1200", ['banned'] = true },
	{ ['name'] = "polmav", ['banned'] = true },
	-- PARAMEDICO
	{ ['name'] = "emstalker", ['banned'] = true },
	{ ['name'] = "ambulance", ['banned'] = true },
	{ ['name'] = "palmav", ['banned'] = true },
	-- CARROS NORMAIS
	{ ['name'] = "futo", ['banned'] = false },
	{ ['name'] = "jester", ['banned'] = false },
	{ ['name'] = "kuruma", ['banned'] = false },
	{ ['name'] = "blista", ['banned'] = false },
	{ ['name'] = "brioso", ['banned'] = false },
	{ ['name'] = "dilettante", ['banned'] = false },
	{ ['name'] = "issi2", ['banned'] = false },
	{ ['name'] = "panto", ['banned'] = false },
	{ ['name'] = "prairie", ['banned'] = false },
	{ ['name'] = "rhapsody", ['banned'] = false },
	{ ['name'] = "cogcabrio", ['banned'] = false },
	{ ['name'] = "emperor", ['banned'] = false },
	{ ['name'] = "emperor2", ['banned'] = false },
	{ ['name'] = "phoenix", ['banned'] = false },
	{ ['name'] = "premier", ['banned'] = false },
	{ ['name'] = "glendale", ['banned'] = false },
	{ ['name'] = "intruder", ['banned'] = false },
	{ ['name'] = "exemplar", ['banned'] = false },
	{ ['name'] = "f620", ['banned'] = false },
	{ ['name'] = "felon", ['banned'] = false },
	{ ['name'] = "ingot", ['banned'] = false },
	{ ['name'] = "felon2", ['banned'] = false },
	{ ['name'] = "jackal", ['banned'] = false },
	{ ['name'] = "oracle", ['banned'] = false },
	{ ['name'] = "oracle2", ['banned'] = false },
	{ ['name'] = "sentinel", ['banned'] = false },
	{ ['name'] = "sentinel2", ['banned'] = false },
	{ ['name'] = "windsor", ['banned'] = false },
	{ ['name'] = "windsor2", ['banned'] = false },
	{ ['name'] = "zion", ['banned'] = false },
	{ ['name'] = "zion2", ['banned'] = false },
	{ ['name'] = "blade", ['banned'] = false },
	{ ['name'] = "buccaneer", ['banned'] = false },
	{ ['name'] = "buccaneer2", ['banned'] = false },
	{ ['name'] = "primo", ['banned'] = false },
	{ ['name'] = "primo2", ['banned'] = false },
	{ ['name'] = "chino", ['banned'] = false },
	{ ['name'] = "chino2", ['banned'] = false },
	{ ['name'] = "coquette3", ['banned'] = false },
	{ ['name'] = "dominator", ['banned'] = false },
	{ ['name'] = "dominator2", ['banned'] = false },
	{ ['name'] = "dukes", ['banned'] = false },
	{ ['name'] = "faction", ['banned'] = false },
	{ ['name'] = "faction2", ['banned'] = false },
	{ ['name'] = "faction3", ['banned'] = false },
	{ ['name'] = "gauntlet", ['banned'] = false },
	{ ['name'] = "gauntlet2", ['banned'] = false },
	{ ['name'] = "hermes", ['banned'] = false },
	{ ['name'] = "hotknife", ['banned'] = false },
	{ ['name'] = "moonbeam", ['banned'] = false },
	{ ['name'] = "moonbeam2", ['banned'] = false },
	{ ['name'] = "nightshade", ['banned'] = false },
	{ ['name'] = "picador", ['banned'] = false },
	{ ['name'] = "ruiner", ['banned'] = false },
	{ ['name'] = "sabregt", ['banned'] = false },
	{ ['name'] = "sabregt2", ['banned'] = false },
	{ ['name'] = "gburrito", ['banned'] = false },
	{ ['name'] = "slamvan", ['banned'] = false },
	{ ['name'] = "slamvan2", ['banned'] = false },
	{ ['name'] = "slamvan3", ['banned'] = false },
	{ ['name'] = "stalion", ['banned'] = false },
	{ ['name'] = "stalion2", ['banned'] = false },
	{ ['name'] = "tampa", ['banned'] = false },
	{ ['name'] = "vigero", ['banned'] = false },
	{ ['name'] = "virgo", ['banned'] = false },
	{ ['name'] = "virgo2", ['banned'] = false },
	{ ['name'] = "virgo3", ['banned'] = false },
	{ ['name'] = "voodoo", ['banned'] = false },
	{ ['name'] = "voodoo2", ['banned'] = false },
	{ ['name'] = "yosemite", ['banned'] = false },
	{ ['name'] = "bfinjection", ['banned'] = false },
	{ ['name'] = "bifta", ['banned'] = false },
	{ ['name'] = "bodhi2", ['banned'] = false },
	{ ['name'] = "brawler", ['banned'] = false },
	{ ['name'] = "trophytruck", ['banned'] = false },
	{ ['name'] = "trophytruck2", ['banned'] = false },
	{ ['name'] = "dubsta3", ['banned'] = false },
	{ ['name'] = "mesa3", ['banned'] = false },
	{ ['name'] = "rancherxl", ['banned'] = false },
	{ ['name'] = "rebel", ['banned'] = false },
	{ ['name'] = "rebel2", ['banned'] = false },
	{ ['name'] = "riata", ['banned'] = false },
	{ ['name'] = "dloader", ['banned'] = false },
	{ ['name'] = "ratloader", ['banned'] = false },
	{ ['name'] = "sandking", ['banned'] = false },
	{ ['name'] = "sandking2", ['banned'] = false },
	{ ['name'] = "baller", ['banned'] = false },
	{ ['name'] = "baller2", ['banned'] = false },
	{ ['name'] = "baller3", ['banned'] = false },
	{ ['name'] = "baller4", ['banned'] = false },
	{ ['name'] = "baller5", ['banned'] = false },
	{ ['name'] = "baller6", ['banned'] = false },
	{ ['name'] = "bjxl", ['banned'] = false },
	{ ['name'] = "cavalcade", ['banned'] = false },
	{ ['name'] = "cavalcade2", ['banned'] = false },
	{ ['name'] = "contender", ['banned'] = false },
	{ ['name'] = "dubsta", ['banned'] = false },
	{ ['name'] = "dubsta2", ['banned'] = false },
	{ ['name'] = "fq2", ['banned'] = false },
	{ ['name'] = "granger", ['banned'] = false },
	{ ['name'] = "gresley", ['banned'] = false },
	{ ['name'] = "habanero", ['banned'] = false },
	{ ['name'] = "seminole", ['banned'] = false },
	{ ['name'] = "serrano", ['banned'] = false },
	{ ['name'] = "xls", ['banned'] = false },
	{ ['name'] = "xls2", ['banned'] = false },
	{ ['name'] = "asea", ['banned'] = false },
	{ ['name'] = "asterope", ['banned'] = false },
	{ ['name'] = "cog55", ['banned'] = false },
	{ ['name'] = "cog552", ['banned'] = false },
	{ ['name'] = "cognoscenti", ['banned'] = false },
	{ ['name'] = "cognoscenti2", ['banned'] = false },
	{ ['name'] = "stanier", ['banned'] = false },
	{ ['name'] = "stratum", ['banned'] = false },
	{ ['name'] = "superd", ['banned'] = false },
	{ ['name'] = "surge", ['banned'] = false },
	{ ['name'] = "tailgater", ['banned'] = false },
	{ ['name'] = "warrener", ['banned'] = false },
	{ ['name'] = "washington", ['banned'] = false },
	{ ['name'] = "alpha", ['banned'] = false },
	{ ['name'] = "banshee", ['banned'] = false },
	{ ['name'] = "bestiagts", ['banned'] = false },
	{ ['name'] = "blista2", ['banned'] = false },
	{ ['name'] = "blista3", ['banned'] = false },
	{ ['name'] = "buffalo", ['banned'] = false },
	{ ['name'] = "buffalo2", ['banned'] = false },
	{ ['name'] = "buffalo3", ['banned'] = false },
	{ ['name'] = "carbonizzare", ['banned'] = false },
	{ ['name'] = "comet2", ['banned'] = false },
	{ ['name'] = "comet3", ['banned'] = false },
	{ ['name'] = "comet5", ['banned'] = false },
	{ ['name'] = "coquette", ['banned'] = false },
	{ ['name'] = "elegy", ['banned'] = false },
	{ ['name'] = "elegy2", ['banned'] = false },
	{ ['name'] = "feltzer2", ['banned'] = false },
	{ ['name'] = "furoregt", ['banned'] = false },
	{ ['name'] = "fusilade", ['banned'] = false },
	{ ['name'] = "futo", ['banned'] = false },
	{ ['name'] = "jester", ['banned'] = false },
	{ ['name'] = "khamelion", ['banned'] = false },
	{ ['name'] = "massacro", ['banned'] = false },
	{ ['name'] = "massacro2", ['banned'] = false },
	{ ['name'] = "ninef", ['banned'] = false},
	{ ['name'] = "ninef2", ['banned'] = false },
	{ ['name'] = "omnis", ['banned'] = false },
	{ ['name'] = "pariah", ['banned'] = false },
	{ ['name'] = "penumbra", ['banned'] = false },
	{ ['name'] = "raiden", ['banned'] = false },
	{ ['name'] = "rapidgt", ['banned'] = false },
	{ ['name'] = "rapidgt2",['banned'] = false },
	{ ['name'] = "ruston", ['banned'] = false },
	{ ['name'] = "schafter3", ['banned'] = false },
	{ ['name'] = "schafter4", ['banned'] = false },
	{ ['name'] = "schafter5", ['banned'] = false },
	{ ['name'] = "schwarzer", ['banned'] = false },
	{ ['name'] = "sentinel3", ['banned'] = false },
	{ ['name'] = "seven70", ['banned'] = false },
	{ ['name'] = "specter", ['banned'] = false },
	{ ['name'] = "specter2", ['banned'] = false },
	{ ['name'] = "streiter", ['banned'] = false },
	{ ['name'] = "sultan", ['banned'] = false },
	{ ['name'] = "surano", ['banned'] = false },
	{ ['name'] = "tampa2", ['banned'] = false },
	{ ['name'] = "tropos",  ['banned'] = false },
	{ ['name'] = "verlierer2", ['banned'] = false },
	{ ['name'] = "btype", ['banned'] = false },
	{ ['name'] = "btype2", ['banned'] = false },
	{ ['name'] = "btype3", ['banned'] = false },
	{ ['name'] = "casco", ['banned'] = false },
	{ ['name'] = "cheetah", ['banned'] = false },
	{ ['name'] = "coquette2", ['banned'] = false },
	{ ['name'] = "feltzer3", ['banned'] = false },
	{ ['name'] = "gt500", ['banned'] = false },
	{ ['name'] = "infernus2", ['banned'] = false },
	{ ['name'] = "jb700", ['banned'] = false },
	{ ['name'] = "mamba", ['banned'] = false },
	{ ['name'] = "manana", ['banned'] = false },
	{ ['name'] = "monroe", ['banned'] = false },
	{ ['name'] = "peyote", ['banned'] = false },
	{ ['name'] = "pigalle", ['banned'] = false },
	{ ['name'] = "rapidgt3", ['banned'] = false },
	{ ['name'] = "retinue", ['banned'] = false },
	{ ['name'] = "stinger", ['banned'] = false },
	{ ['name'] = "stingergt", ['banned'] = false },
	{ ['name'] = "torero", ['banned'] = false },
	{ ['name'] = "tornado", ['banned'] = false },
	{ ['name'] = "tornado2", ['banned'] = false },
	{ ['name'] = "tornado5", ['banned'] = false },
	{ ['name'] = "tornado6", ['banned'] = false },
	{ ['name'] = "turismo2", ['banned'] = false },
	{ ['name'] = "ztype", ['banned'] = false },
	{ ['name'] = "adder", ['banned'] = false },
	{ ['name'] = "autarch", ['banned'] = false },
	{ ['name'] = "banshee2", ['banned'] = false },
	{ ['name'] = "bullet",  ['banned'] = false },
	{ ['name'] = "cheetah2", ['banned'] = false },
	{ ['name'] = "entityxf", ['banned'] = false },
	{ ['name'] = "fmj", ['banned'] = false },
	{ ['name'] = "gp1", ['banned'] = false },
	{ ['name'] = "infernus", ['banned'] = false },
	{ ['name'] = "nero", ['banned'] = false },
	{ ['name'] = "nero2", ['banned'] = false },
	{ ['name'] = "osiris", ['banned'] = false },
	{ ['name'] = "penetrator", ['banned'] = false },
	{ ['name'] = "pfister811", ['banned'] = false },
	{ ['name'] = "reaper", ['banned'] = false },
	{ ['name'] = "mobi", ['banned'] = false },
	{ ['name'] = "jettagli", ['banned'] = false },
	{ ['name'] = "hb20", ['banned'] = false },
	{ ['name'] = "160", ['banned'] = false },
	{ ['name'] = "sc1", ['banned'] = false },
	{ ['name'] = "sultanrs", ['banned'] = false },
	{ ['name'] = "t20", ['banned'] = false },
	{ ['name'] = "tempesta", ['banned'] = false },
	{ ['name'] = "turismor", ['banned'] = false },
	{ ['name'] = "tyrus", ['banned'] = false },
	{ ['name'] = "vacca", ['banned'] = false },
	{ ['name'] = "visione", ['banned'] = false },
	{ ['name'] = "voltic", ['banned'] = false },
	{ ['name'] = "zentorno", ['banned'] = false },
	{ ['name'] = "sadler", ['banned'] = false },
	{ ['name'] = "bison", ['banned'] = false },
	{ ['name'] = "bison2", ['banned'] = false },
	{ ['name'] = "bobcatxl", ['banned'] = false },
	{ ['name'] = "burrito", ['banned'] = false },
	{ ['name'] = "burrito2", ['banned'] = false },
	{ ['name'] = "burrito3", ['banned'] = false },
	{ ['name'] = "burrito4", ['banned'] = false },
	{ ['name'] = "minivan", ['banned'] = false },
	{ ['name'] = "minivan2", ['banned'] = false },
	{ ['name'] = "paradise", ['banned'] = false },
	{ ['name'] = "pony", ['banned'] = false },
	{ ['name'] = "pony2", ['banned'] = false },
	{ ['name'] = "rumpo", ['banned'] = false },
	{ ['name'] = "rumpo2", ['banned'] = false },
	{ ['name'] = "rumpo3", ['banned'] = false },
	{ ['name'] = "speedo", ['banned'] = false },
	-- viaturas
	{ ['name'] = "amggtsmansory", ['banned'] = false },
	{ ['name'] = "LOclassx", ['banned'] = false },
	{ ['name'] = "novakpol", ['banned'] = false },
	{ ['name'] = "poliziatahoe", ['banned'] = false },
	{ ['name'] = "WRafricat", ['banned'] = false },
	{ ['name'] = "WRsxr", ['banned'] = false },
	{ ['name'] = "WRxclass6", ['banned'] = false },
	{ ['name'] = "surfer", ['banned'] = false },
	{ ['name'] = "youga", ['banned'] = false },
	{ ['name'] = "youga2", ['banned'] = false },
	{ ['name'] = "rebel", ['banned'] = false },
	{ ['name'] = "tractor2", ['banned'] = false },
	{ ['name'] = "huntley", ['banned'] = false },
	{ ['name'] = "landstalker", ['banned'] = false },
	{ ['name'] = "mesa", ['banned'] = false },
	{ ['name'] = "patriot", ['banned'] = false },
	{ ['name'] = "radi", ['banned'] = false },
	{ ['name'] = "rocoto", ['banned'] = false },
	{ ['name'] = "tyrant", ['banned'] = false },
	{ ['name'] = "entity2", ['banned'] = false },
	{ ['name'] = "cheburek", ['banned'] = false },
	{ ['name'] = "hotring", ['banned'] = false },
	{ ['name'] = "jester3", ['banned'] = false },
	{ ['name'] = "flashgt", ['banned'] = false },
	{ ['name'] = "ellie", ['banned'] = false },
	{ ['name'] = "michelli", ['banned'] = false },
	{ ['name'] = "fagaloa", ['banned'] = false },
	{ ['name'] = "dominator2", ['banned'] = false },
	{ ['name'] = "dominator3", ['banned'] = false },
	{ ['name'] = "issi3", ['banned'] = false },
	{ ['name'] = "taipan", ['banned'] = false },
	{ ['name'] = "gb200", ['banned'] = false },
	{ ['name'] = "stretch", ['banned'] = false },
	{ ['name'] = "guardian", ['banned'] = false },
	{ ['name'] = "kamacho", ['banned'] = false },
	{ ['name'] = "neon", ['banned'] = false },
	{ ['name'] = "cyclone", ['banned'] = false },
	{ ['name'] = "italigtb", ['banned'] = false },
	{ ['name'] = "italigtb2", ['banned'] = false },
	{ ['name'] = "vagner", ['banned'] = false },
	{ ['name'] = "xa21", ['banned'] = false },
	{ ['name'] = "tezeract", ['banned'] = false },
	{ ['name'] = "prototipo", ['banned'] = false },
	{ ['name'] = "patriot2", ['banned'] = false },
	{ ['name'] = "stafford", ['banned'] = false },
	{ ['name'] = "swinger", ['banned'] = false },
	{ ['name'] = "clique", ['banned'] = false },
	{ ['name'] = "deveste", ['banned'] = false },
	{ ['name'] = "deviant", ['banned'] = false },
	{ ['name'] = "impaler", ['banned'] = false },
	{ ['name'] = "italigto", ['banned'] = false },
	{ ['name'] = "schlagen", ['banned'] = false },
	{ ['name'] = "toros", ['banned'] = false },
	{ ['name'] = "tulip", ['banned'] = false },
	{ ['name'] = "vamos", ['banned'] = false },
	{ ['name'] = "freecrawler", ['banned'] = false },	
	{ ['name'] = "fugitive", ['banned'] = false },
	{ ['name'] = "le7b", ['banned'] = false },
	{ ['name'] = "lurcher", ['banned'] = false },
	{ ['name'] = "lynx", ['banned'] = false },
	{ ['name'] = "raptor", ['banned'] = false },
	{ ['name'] = "sheava", ['banned'] = false },
	{ ['name'] = "z190", ['banned'] = false },
	{ ['name'] = "akuma", ['banned'] = false },
	{ ['name'] = "avarus", ['banned'] = false },
	{ ['name'] = "bagger", ['banned'] = false },
	{ ['name'] = "bati", ['banned'] = false },
	{ ['name'] = "bati2", ['banned'] = false },
	{ ['name'] = "bf400", ['banned'] = false },
	{ ['name'] = "carbonrs", ['banned'] = false },
	{ ['name'] = "chimera", ['banned'] = false },
	{ ['name'] = "cliffhanger", ['banned'] = false },
	{ ['name'] = "daemon", ['banned'] = false },
	{ ['name'] = "daemon2", ['banned'] = false },
	{ ['name'] = "defiler", ['banned'] = false },
	{ ['name'] = "diablous", ['banned'] = false },
	{ ['name'] = "diablous2", ['banned'] = false },
	{ ['name'] = "double",  ['banned'] = false },
	{ ['name'] = "enduro", ['banned'] = false },
	{ ['name'] = "esskey", ['banned'] = false },
	{ ['name'] = "faggio",  ['banned'] = false },
	{ ['name'] = "faggio2", ['banned'] = false },
	{ ['name'] = "faggio3", ['banned'] = false },
	{ ['name'] = "fcr", ['banned'] = false },
	{ ['name'] = "fcr2", ['banned'] = false },
	{ ['name'] = "gargoyle", ['banned'] = false },
	{ ['name'] = "hakuchou", ['banned'] = false },
	{ ['name'] = "hakuchou2", ['banned'] = false },
	{ ['name'] = "hexer", ['banned'] = false },
	{ ['name'] = "innovation", ['banned'] = false },
	{ ['name'] = "lectro", ['banned'] = false },
	{ ['name'] = "manchez", ['banned'] = false },
	{ ['name'] = "nemesis", ['banned'] = false },
	{ ['name'] = "nightblade", ['banned'] = false },
	{ ['name'] = "pcj", ['banned'] = false },
	{ ['name'] = "ruffian", ['banned'] = false },
	{ ['name'] = "sanchez", ['banned'] = false },
	{ ['name'] = "sanchez2", ['banned'] = false },
	{ ['name'] = "sanctus", ['banned'] = false },
	{ ['name'] = "sovereign", ['banned'] = false },
	{ ['name'] = "thrust", ['banned'] = false },
	{ ['name'] = "vader", ['banned'] = false },
	{ ['name'] = "vindicator", ['banned'] = false },
	{ ['name'] = "vortex", ['banned'] = false },
	{ ['name'] = "wolfsbane", ['banned'] = false },
	{ ['name'] = "zombiea", ['banned'] = false },
	{ ['name'] = "zombieb", ['banned'] = false },
	{ ['name'] = "blazer", ['banned'] = false },
	{ ['name'] = "blazer4", ['banned'] = false },
	{ ['name'] = "shotaro", ['banned'] = false },
	{ ['name'] = "ratbike", ['banned'] = false },
	{ ['name'] = "pbus", ['banned'] = true },
	{ ['name'] = "mule4", ['banned'] = false },
	{ ['name'] = "rallytruck", ['banned'] = false },
	{ ['name'] = "riot", ['banned'] = true },
	{ ['name'] = "coach", ['banned'] = true },
	{ ['name'] = "bus", ['banned'] = true },
	{ ['name'] = "flatbed", ['banned'] = true },
	{ ['name'] = "towtruck", ['banned'] = true },
	{ ['name'] = "towtruck2", ['banned'] = true },
	{ ['name'] = "ratloader", ['banned'] = true },
	{ ['name'] = "ratloader2", ['banned'] = false },
	{ ['name'] = "rubble", ['banned'] = true },
	{ ['name'] = "taxi", ['banned'] = true },
	{ ['name'] = "boxville4", ['banned'] = false },
	{ ['name'] = "trash2", ['banned'] = false },
	{ ['name'] = "tiptruck", ['banned'] = false },
	{ ['name'] = "scorcher", ['banned'] = true },
	{ ['name'] = "tribike", ['banned'] = true },
	{ ['name'] = "tribike2", ['banned'] = true },
	{ ['name'] = "tribike3", ['banned'] = true },
	{ ['name'] = "fixter", ['banned'] = true },
	{ ['name'] = "cruiser", ['banned'] = true },
	{ ['name'] = "bmx", ['banned'] = true },
	{ ['name'] = "dinghy", ['banned'] = true },
	{ ['name'] = "jetmax", ['banned'] = true },
	{ ['name'] = "marquis", ['banned'] = true },
	{ ['name'] = "seashark3", ['banned'] = true },
	{ ['name'] = "speeder", ['banned'] = true },
	{ ['name'] = "speeder2", ['banned'] = true },
	{ ['name'] = "squalo", ['banned'] = true },
	{ ['name'] = "suntrap", ['banned'] = true },
	{ ['name'] = "toro", ['banned'] = true },
	{ ['name'] = "toro2", ['banned'] = true },
	{ ['name'] = "tropic", ['banned'] = true },
	{ ['name'] = "tropic2", ['banned'] = true },
	{ ['name'] = "phantom", ['banned'] = true },
	{ ['name'] = "packer", ['banned'] = true },
	{ ['name'] = "supervolito", ['banned'] = true },
	{ ['name'] = "supervolito2", ['banned'] = true },
	{ ['name'] = "seasparrow", ['banned'] = true },
	{ ['name'] = "cuban800", ['banned'] = true },
	{ ['name'] = "mammatus", ['banned'] = true },
	{ ['name'] = "vestra", ['banned'] = true },
	{ ['name'] = "velum2", ['banned'] = true },
	{ ['name'] = "buzzard2", ['banned'] = true },
	{ ['name'] = "frogger", ['banned'] = true },
	{ ['name'] = "maverick", ['banned'] = true },
	{ ['name'] = "tanker2", ['banned'] = true },
	{ ['name'] = "armytanker", ['banned'] = true },
	{ ['name'] = "tvtrailer", ['banned'] = true },
	{ ['name'] = "trailerlogs", ['banned'] = true },
	{ ['name'] = "tr4", ['banned'] = true },
	{ ['name'] = "coquettessd", ['banned'] = true },
	{ ['name'] = "carbonssd", ['banned'] = true },
	{ ['name'] = "caracarastd", ['banned'] = true },
	{ ['name'] = "komodahc", ['banned'] = true },
	{ ['name'] = "jugularspd", ['banned'] = true },
	{ ['name'] = "sugoispd", ['banned'] = true },
	{ ['name'] = "poliziaheli", ['banned'] = true },
	-- polizia SUL novo
	{ ['name'] = "WRa45", ['banned'] = true },
	{ ['name'] = "WRbmwx7", ['banned'] = true },
	{ ['name'] = "WRc7pm", ['banned'] = true },
	{ ['name'] = "WRcorollapm", ['banned'] = true },
	{ ['name'] = "xxxxxcore", ['banned'] = true },
	{ ['name'] = "xxxxxpol", ['banned'] = true },
	{ ['name'] = "WRr1200pol", ['banned'] = true },
	-- PARAMEDICO
	{ ['name'] = "emstalker", ['banned'] = true },
	{ ['name'] = "ambulance", ['banned'] = true },
	{ ['name'] = "palmav", ['banned'] = true },
	
	-- PARAMEDICO novo
	{ ['name'] = "r1200rtp", ['banned'] = true },
	{ ['name'] = "qrv", ['banned'] = true },
	{ ['name'] = "raiosprinter", ['banned'] = true },

	{ ['name'] = "pdhell", ['hash'] = GetHashKey('pdhell'), ['banned'] = true },
	{ ['name'] = "ghispo2", ['hash'] = GetHashKey('ghispo2'), ['banned'] = true },
	{ ['name'] = "pdfocus", ['hash'] = GetHashKey('pdfocus'), ['banned'] = true },
	{ ['name'] = "pdtaurus", ['hash'] = GetHashKey('pdtaurus'), ['banned'] = true },
	{ ['name'] = "pdtahoe", ['hash'] = GetHashKey('pdtahoe'), ['banned'] = true },
	{ ['name'] = "gt63pol", ['hash'] = -1020523721, ['banned'] = true },
	{ ['name'] = "dodgepol", ['hash'] = 872350736, ['banned'] = true },
	{ ['name'] = "amarokpol", ['hash'] = -1396559247, ['banned'] = true },
	{ ['name'] = "africatpol", ['hash'] = 1172001515, ['banned'] = true },
	{ ['name'] = "mustangpol", ['hash'] = -183056702, ['banned'] = true },
	{ ['name'] = "a45pol", ['hash'] = 1477164877, ['banned'] = true },
	{ ['name'] = "amggtrpolizia", ['hash'] = -1620637, ['banned'] = true },
	{ ['name'] = "gle63spolizia", ['hash'] = 1480898933, ['banned'] = true },
	{ ['name'] = "c63p17", ['hash'] = 85016747, ['banned'] = true },
	{ ['name'] = "CLS53", ['hash'] = -2052918278, ['banned'] = true },
	{ ['name'] = "classexp", ['hash'] = -621239469, ['banned'] = true },
	{ ['name'] = "cla45spolizia", ['hash'] = 1771803342, ['banned'] = true },
	{ ['name'] = "WRc8", ['hash'] = 1001000391, ['banned'] = true },
	{ ['name'] = "sprinterhp", ['hash'] = -59927658, ['banned'] = true },
	{ ['name'] = "cb500p", ['hash'] = -1801333578, ['banned'] = true },

	{ ['name'] = "ram", ['hash'] = GetHashKey('ram'), ['banned'] = true },
	{ ['name'] = "kawasaki", ['hash'] = GetHashKey('kawasaki'), ['banned'] = true },
	{ ['name'] = "chevyss", ['hash'] = GetHashKey('chevyss'), ['banned'] = true },
	{ ['name'] = "spincivil", ['hash'] = GetHashKey('spincivil'), ['banned'] = true },
	{ ['name'] = "polmav", ['hash'] = GetHashKey('polmav'), ['banned'] = true },
	{ ['name'] = "as350", ['hash'] = 1346171487, ['banned'] = true },
	{ ['name'] = "as350pm", ['hash'] = 816132237, ['banned'] = true },
	{ ['name'] = "uh1nasa", ['hash'] = -2077517328, ['banned'] = true },
	{ ['name'] = "uh1core", ['hash'] = 30018912, ['banned'] = true },
	{ ['name'] = "policeb", ['hash'] = -34623805, ['banned'] = true },

	{ ['name'] = "paramedicoambu", ['hash'] = -792745162, ['banned'] = true },
	{ ['name'] = "paramedicobmwr1200", ['hash'] = 2049135429, ['banned'] = true },
	{ ['name'] = "paramedicotahoe", ['hash'] = 2040793826, ['banned'] = true },
	{ ['name'] = "paramedicocharger2014", ['hash'] = 108063727, ['banned'] = true },
	{ ['name'] = "paramedicoheli", ['hash'] = 2020690903, ['banned'] = true },

	{ ['name'] = "pbus", ['hash'] = -2007026063, ['banned'] = true },
	{ ['name'] = "mule3", ['hash'] = -2052737935, ['banned'] = false },
	{ ['name'] = "rallytruck", ['hash'] = -2103821244, ['banned'] = false },
	{ ['name'] = "riot", ['hash'] = -1205689942, ['banned'] = true },
	{ ['name'] = "coach", ['hash'] = -2072933068, ['banned'] = true },
	{ ['name'] = "bus", ['hash'] = -713569950, ['banned'] = true },
	{ ['name'] = "flatbed", ['hash'] = 1353720154, ['banned'] = true },
	{ ['name'] = "towtruck", ['hash'] = -1323100960, ['banned'] = true },
	{ ['name'] = "towtruck2", ['hash'] = -442313018, ['banned'] = true },
	{ ['name'] = "ratloader", ['hash'] = -667151410, ['banned'] = true },
	{ ['name'] = "ratloader2", ['hash'] = -589178377, ['banned'] = false },
	{ ['name'] = "rubble", ['hash'] = -1705304628, ['banned'] = true },
	{ ['name'] = "taxi", ['hash'] = -956048545, ['banned'] = true },
	{ ['name'] = "boxville4", ['hash'] = 444171386, ['banned'] = false },
	{ ['name'] = "trash2", ['hash'] = -1255698084, ['banned'] = false },
	{ ['name'] = "tiptruck", ['hash'] = 48339065, ['banned'] = false },
	{ ['name'] = "scorcher", ['hash'] = -186537451, ['banned'] = true },
	{ ['name'] = "tribike", ['hash'] = 1127861609, ['banned'] = true },
	{ ['name'] = "tribike2", ['hash'] = -1233807380, ['banned'] = true },
	{ ['name'] = "tribike3", ['hash'] = -400295096, ['banned'] = true },
	{ ['name'] = "fixter", ['hash'] = -836512833, ['banned'] = true },
	{ ['name'] = "cruiser", ['hash'] = 448402357, ['banned'] = true },
	{ ['name'] = "bmx", ['hash'] = 1131912276, ['banned'] = true },
	{ ['name'] = "dinghy", ['hash'] = 1033245328, ['banned'] = true },
	{ ['name'] = "jetmax", ['hash'] = 861409633, ['banned'] = true },
	{ ['name'] = "marquis", ['hash'] = -1043459709, ['banned'] = true },
	{ ['name'] = "seashark3", ['hash'] = -311022263, ['banned'] = true },
	{ ['name'] = "speeder", ['hash'] = 231083307, ['banned'] = true },
	{ ['name'] = "speeder2", ['hash'] = 437538602, ['banned'] = true },
	{ ['name'] = "squalo", ['hash'] = 400514754, ['banned'] = true },
	{ ['name'] = "suntrap", ['hash'] = -282946103, ['banned'] = true },
	{ ['name'] = "toro", ['hash'] = 1070967343, ['banned'] = true },
	{ ['name'] = "toro2", ['hash'] = 908897389, ['banned'] = true },
	{ ['name'] = "tropic", ['hash'] = 290013743, ['banned'] = true },
	{ ['name'] = "tropic2", ['hash'] = 1448677353, ['banned'] = true },
	{ ['name'] = "phantom", ['hash'] = -2137348917, ['banned'] = true },
	{ ['name'] = "packer", ['hash'] = 569305213, ['banned'] = true },
	{ ['name'] = "supervolito", ['hash'] = 710198397, ['banned'] = true },
	{ ['name'] = "supervolito2", ['hash'] = -1671539132, ['banned'] = true },
	{ ['name'] = "seasparrow", ['hash'] = -726768679, ['banned'] = true },
	{ ['name'] = "cuban800", ['hash'] = -644710429, ['banned'] = true },
	{ ['name'] = "mammatus", ['hash'] = -1746576111, ['banned'] = true },
	{ ['name'] = "vestra", ['hash'] = 1341619767, ['banned'] = true },
	{ ['name'] = "velum2", ['hash'] = 1077420264, ['banned'] = true },
	{ ['name'] = "buzzard2", ['hash'] = 745926877, ['banned'] = true },
	{ ['name'] = "frogger", ['hash'] = 744705981, ['banned'] = true },
	{ ['name'] = "maverick", ['hash'] = -1660661558, ['banned'] = true },
	{ ['name'] = "tanker2", ['hash'] = 1956216962, ['banned'] = true },
	{ ['name'] = "armytanker", ['hash'] = -1207431159, ['banned'] = true },
	{ ['name'] = "tvtrailer", ['hash'] = -1770643266, ['banned'] = true },
	{ ['name'] = "trailerlogs", ['hash'] = 2016027501, ['banned'] = true },
	{ ['name'] = "tr4", ['hash'] = 2091594960, ['banned'] = true },

	{ ['name'] = "xt700", ['hash'] = GetHashKey('xt700'), ['banned'] = false },
	{ ['name'] = "WRTiger900", ['hash'] = GetHashKey('WRTiger900'), ['banned'] = false },
	{ ['name'] = "s1000rr", ['hash'] = 436874758, ['banned'] = false },
	{ ['name'] = "r1250pol", ['hash'] = GetHashKey('r1250pol'), ['banned'] = false },
	{ ['name'] = "nissangtr", ['hash'] = -60313827, ['banned'] = false },
	{ ['name'] = "nissangtr2", ['hash'] = 520007028, ['banned'] = false },
	{ ['name'] = "lwgtr", ['hash'] = 590709306, ['banned'] = false },
	{ ['name'] = "nissan370z", ['hash'] = -2015218779, ['banned'] = false },
	{ ['name'] = "dodgecharger", ['hash'] = 986544975, ['banned'] = false },
	{ ['name'] = "ferrariitalia", ['hash'] = -1173768715, ['banned'] = false },
	{ ['name'] = "rmodx6", ['hash'] = 2045784380, ['banned'] = false },
	{ ['name'] = "audirs6", ['hash'] = 1676738519, ['banned'] = false },
	{ ['name'] = "bmwm3f80", ['hash'] = -157095615, ['banned'] = false },
	{ ['name'] = "bmwm4gts", ['hash'] = -13524981, ['banned'] = false },
	{ ['name'] = "bmwm5f90", ['hash'] = 999324520, ['banned'] = false },
	{ ['name'] = "fordmustang", ['hash'] = -1573350092, ['banned'] = false },
	{ ['name'] = "lamborghinihuracan", ['hash'] = 1114244595, ['banned'] = false },
	{ ['name'] = "lancerevolutionx", ['hash'] = 1978088379, ['banned'] = false },
	{ ['name'] = "mazdarx7", ['hash'] = 2034235290, ['banned'] = false },
	{ ['name'] = "nissangtrnismo", ['hash'] = 670022011, ['banned'] = false },
	{ ['name'] = "nissanskyliner34", ['hash'] = -4816535, ['banned'] = false },
	{ ['name'] = "golfgti7", ['hash'] = -2018557295, ['banned'] = false },
	{ ['name'] = "teslaprior", ['hash'] = 351980252, ['banned'] = false },
	{ ['name'] = "toyotasupra", ['hash'] = 723779872, ['banned'] = false },
	{ ['name'] = "mercedesa45", ['hash'] = -740742391, ['banned'] = false },
	{ ['name'] = "focusrs", ['hash'] = 819937652, ['banned'] = false },
	{ ['name'] = "lancerevolution9", ['hash'] = -133349447, ['banned'] = false },
	{ ['name'] = "h2carb", ['hash'] = -1371768796, ['banned'] = false },
	{ ['name'] = "trr", ['hash'] = -333868117, ['banned'] = false },
	{ ['name'] = "lwhuracan", ['hash'] = 1028745873, ['banned'] = false },
	{ ['name'] = "p1", ['hash'] = -189438188, ['banned'] = false },
	{ ['name'] = "i8", ['hash'] = 1718441594, ['banned'] = false },
	{ ['name'] = "bme6tun", ['hash'] = -380714779, ['banned'] = false },
	{ ['name'] = "aperta", ['hash'] = -1481236684, ['banned'] = false },
	{ ['name'] = "bettle", ['hash'] = -498891507, ['banned'] = false },
	{ ['name'] = "senna", ['hash'] = -433961724, ['banned'] = false },
	{ ['name'] = "rmodx6", ['hash'] = 2045784380, ['banned'] = false },
	{ ['name'] = "bnteam", ['hash'] = 113372153, ['banned'] = false },
	{ ['name'] = "rmodlp770", ['hash'] = -1274284606, ['banned'] = false },
	{ ['name'] = "divo", ['hash'] = 1503141430, ['banned'] = false },
	{ ['name'] = "s15", ['hash'] = 1966489524, ['banned'] = false },
	{ ['name'] = "mercedesgt63s", ['hash'] = 1537503531, ['banned'] = false },
	{ ['name'] = "lamtmc", ['hash'] = -264618235, ['banned'] = false },
	{ ['name'] = "vantage", ['hash'] = -1067176722, ['banned'] = false },
	{ ['name'] = "urus", ['hash'] = -520214134, ['banned'] = false },
	{ ['name'] = "amarok", ['hash'] = 493030188, ['banned'] = false },
	{ ['name'] = "slsamg", ['hash'] = 2093958905, ['banned'] = false },
	{ ['name'] = "g65amg", ['hash'] = 104532066, ['banned'] = false },
	{ ['name'] = "celta", ['hash'] = 1995020435, ['banned'] = false },
	{ ['name'] = "eleanor", ['hash'] = 137494285, ['banned'] = false },
	{ ['name'] = "rmodamgc63", ['hash'] = -863499820, ['banned'] = false },
	{ ['name'] = "palameila", ['hash'] = -1315334327, ['banned'] = false },
	{ ['name'] = "bmwm8", ['hash'] = -1404319008, ['banned'] = false },
	{ ['name'] = "ferrari812", ['hash'] = -322014905, ['banned'] = false },
	{ ['name'] = "audir8", ['hash'] = -739058151, ['banned'] = false },
	{ ['name'] = "cbr17", ['hash'] = -982818719, ['banned'] = false },
	{ ['name'] = "f800", ['hash'] = -475284513, ['banned'] = false },
	{ ['name'] = "rsvr16", ['hash'] = -1031680535, ['banned'] = false },
	{ ['name'] = "veneno", ['hash'] = -42051018, ['banned'] = false },
	{ ['name'] = "19ramdonk", ['hash'] = -1824291874, ['banned'] = false },
	{ ['name'] = "silv86", ['hash'] = -304124483, ['banned'] = false },
	{ ['name'] = "bc", ['hash'] = -402398867, ['banned'] = false },
	{ ['name'] = "70camarofn", ['hash'] = 2113322010, ['banned'] = false },
	{ ['name'] = "agerars", ['hash'] = -654239719, ['banned'] = false },
	{ ['name'] = "fc15", ['hash'] = 580861919, ['banned'] = false },
	{ ['name'] = "bbentayga", ['hash'] = 1402024844, ['banned'] = false },
	{ ['name'] = "nissantitan17", ['hash'] = 1221510024, ['banned'] = false },
	{ ['name'] = "regera", ['hash'] = 1085789913, ['banned'] = false },
	{ ['name'] = "911r", ['hash'] = 144259586, ['banned'] = false },
	{ ['name'] = "africat", ['hash'] = 1047274985, ['banned'] = false },
	{ ['name'] = "msohs", ['hash'] = -653358508, ['banned'] = false },
	{ ['name'] = "gt17", ['hash'] = -2011325074, ['banned'] = false },
	{ ['name'] = "19ftype", ['hash'] = 1224601968, ['banned'] = false },
	{ ['name'] = "488gtb", ['hash'] = -1593808613, ['banned'] = false },
	{ ['name'] = "fxxkevo", ['hash'] = 235772231, ['banned'] = false },
	{ ['name'] = "m2", ['hash'] = -1313740730, ['banned'] = false },
	{ ['name'] = "defiant", ['hash'] = 233681897, ['banned'] = false },
	{ ['name'] = "f12tdf", ['hash'] = -1507259850, ['banned'] = false },
	{ ['name'] = "71gtx", ['hash'] = -1863430482, ['banned'] = false },
	{ ['name'] = "porsche992", ['hash'] = 859592619, ['banned'] = false },
	{ ['name'] = "18macan", ['hash'] = -187294055, ['banned'] = false },
	{ ['name'] = "m6e63", ['hash'] = 1270688730, ['banned'] = false },
	{ ['name'] = "180sx", ['hash'] = -1467569396, ['banned'] = false },
	{ ['name'] = "audirs7", ['hash'] = -192929549, ['banned'] = false },
	{ ['name'] = "hondafk8", ['hash'] = 653510754, ['banned'] = false },
	{ ['name'] = "mustangmach1", ['hash'] = -148915999, ['banned'] = false },
	{ ['name'] = "porsche930", ['hash'] = 2009693397, ['banned'] = false },
	{ ['name'] = "raptor2017", ['hash'] = 624514487, ['banned'] = false },
	{ ['name'] = "filthynsx", ['hash'] = -2096912321, ['banned'] = false },
	{ ['name'] = "2018zl1", ['hash'] = -1671973728, ['banned'] = false },
	{ ['name'] = "eclipse", ['hash'] = 1603211447, ['banned'] = false },
	{ ['name'] = "volatus", ['hash'] = -1845487887, ['banned'] = false },
	{ ['name'] = "cargobob2", ['hash'] = 16211617168, ['banned'] = false },
	{ ['name'] = "poliziabmwr1200", ['hash'] = -1624991916, ['banned'] = true },
	{ ['name'] = "vstr", ['hash'] = 1456336509, ['banned'] = false },
	{ ['name'] = "corvettec7", ['hash'] = -986071517, ['banned'] = false },
	{ ['name'] = "bmwm8", ['hash'] = -1404319008, ['banned'] = false },
	{ ['name'] = "maseratif620", ['hash'] = 1244065430, ['banned'] = false },
	{ ['name'] = "ferrari812", ['hash'] = -322014905, ['banned'] = false },
	{ ['name'] = "subarubrz13", ['hash'] = 68304089, ['banned'] = false },
	{ ['name'] = "civictyper", ['hash'] = 2004548589, ['banned'] = false },
	{ ['name'] = "cbb", ['hash'] = 1935444402, ['banned'] = false },
	{ ['name'] = "macan", ['hash'] = 1241978166, ['banned'] = false },
	{ ['name'] = "pgt3", ['hash'] = 54739228, ['banned'] = false },
	{ ['name'] = "bnr34", ['hash'] = -1430138530, ['banned'] = false },
	{ ['name'] = "tsgr20", ['hash'] = 1762839497, ['banned'] = false },
	{ ['name'] = "urus", ['hash'] = -520214134, ['banned'] = false },
	{ ['name'] = "r1", ['hash'] = GetHashKey("r1"), ['banned'] = false },
	{ ['name'] = "mk3vr6", ['hash'] = GetHashKey("mk3vr6"), ['banned'] = false },

	{ ['name'] = "barricada", ['hash'] = GetHashKey("barricada"), ['banned'] = false },
	{ ['name'] = "caminhao", ['hash'] = GetHashKey("caminhao"), ['banned'] = false },
	{ ['name'] = "fox", ['hash'] = GetHashKey("fox"), ['banned'] = false },
	{ ['name'] = "gol", ['hash'] = GetHashKey("gol"), ['banned'] = false },
	{ ['name'] = "hb20", ['hash'] = GetHashKey("hb20"), ['banned'] = false },
	{ ['name'] = "jettagli", ['hash'] = GetHashKey("jettagli"), ['banned'] = false },
	{ ['name'] = "mobi", ['hash'] = GetHashKey("mobi"), ['banned'] = false },
	{ ['name'] = "gcmcity14", ['hash'] = GetHashKey("gcmcity14"), ['banned'] = false },
	{ ['name'] = "hondacivic20", ['hash'] = GetHashKey("hondacivic20"), ['banned'] = false },
	{ ['name'] = "up", ['hash'] = GetHashKey("up"), ['banned'] = false },
	{ ['name'] = "gs310", ['hash'] = GetHashKey("gs310"), ['banned'] = false },
	{ ['name'] = "hornet", ['hash'] = GetHashKey("hornet"), ['banned'] = false },
	{ ['name'] = "20xmax", ['hash'] = GetHashKey("20xmax"), ['banned'] = false },
	{ ['name'] = "160", ['hash'] = GetHashKey("160"), ['banned'] = false },
	{ ['name'] = "bros", ['hash'] = GetHashKey("bros"), ['banned'] = false },
	{ ['name'] = "xj6", ['hash'] = GetHashKey("xj6"), ['banned'] = false },
	{ ['name'] = "xt", ['hash'] = GetHashKey("xt"), ['banned'] = false },
	{ ['name'] = "sonata20", ['hash'] = GetHashKey("sonata20"), ['banned'] = false },
	{ ['name'] = "fordfocus", ['hash'] = GetHashKey("fordfocus"), ['banned'] = false },
	{ ['name'] = "panamera17turbo", ['hash'] = GetHashKey("panamera17turbo"), ['banned'] = false },
	{ ['name'] = "rs3", ['hash'] = GetHashKey("rs3"), ['banned'] = false },
	{ ['name'] = "meccx", ['hash'] = GetHashKey("meccx"), ['banned'] = false },
	{ ['name'] = "giulia", ['hash'] = GetHashKey("giulia"), ['banned'] = false },
	{ ['name'] = "euros", ['hash'] = GetHashKey("euros"), ['banned'] = false },
	{ ['name'] = "a6", ['hash'] = GetHashKey("a6"), ['banned'] = false },
	{ ['name'] = "c63", ['hash'] = GetHashKey("c63"), ['banned'] = false },
	{ ['name'] = "hiluxsw4", ['hash'] = GetHashKey("hiluxsw4"), ['banned'] = false },
	{ ['name'] = "mk7", ['hash'] = GetHashKey("mk7"), ['banned'] = false },
	{ ['name'] = "q8", ['hash'] = GetHashKey("q8"), ['banned'] = false },
	{ ['name'] = "subaruimpreza", ['hash'] = GetHashKey("subaruimpreza"), ['banned'] = false },
}
-----------------------------------------------------------------------------------------------------------------------------------------
-- VEHLIST
-----------------------------------------------------------------------------------------------------------------------------------------
function tvRP.vehList(radius)
    local ped = PlayerPedId()
    local veh = GetVehiclePedIsUsing(ped)
    if not IsPedInAnyVehicle(ped) then
        veh = tvRP.getNearestVehicle(radius)
    end
    if IsEntityAVehicle(veh) then
        local lock = GetVehicleDoorLockStatus(veh)
        local trunk = GetVehicleDoorAngleRatio(v,5)
        local x,y,z = table.unpack(GetEntityCoords(ped))
        for k,v in pairs(vehList) do
            if GetHashKey(v.name) == GetEntityModel(veh) then 
                if v.name then
                    local tuning = { GetNumVehicleMods(veh,13),GetNumVehicleMods(veh,12),GetNumVehicleMods(veh,15),GetNumVehicleMods(veh,11),GetNumVehicleMods(veh,16) }
                    return veh,VehToNet(veh),GetVehicleNumberPlateText(veh),v.name,lock,v.banned,trunk,GetDisplayNameFromVehicleModel(v.name),GetStreetNameFromHashKey(GetStreetNameAtCoord(x,y,z)),tuning
                end
            end
        end
    end
end